main:
	gcc sesli_sessiz_harf_sayar.c -o sesli_sessiz_harf_sayar.out

windows:
	x86_64-w64-mingw32-gcc sesli_sessiz_harf_sayar.c -o sesli_sessiz_harf_sayar.exe

run:
	./sesli_sessiz_harf_sayar.out

run_windows:
	wine ./sesli_sessiz_harf_sayar.exe

clean:
	rm sesli_sessiz_harf_sayar.out sesli_sessiz_harf_sayar.exe