main:
	gcc sayi_tahmin_oyunu.c -o sayi_tahmin_oyunu.out

windows:
	x86_64-w64-mingw32-gcc sayi_tahmin_oyunu.c -o sayi_tahmin_oyunu.exe

run:
	./sayi_tahmin_oyunu.out

run_windows:
	wine ./sayi_tahmin_oyunu.exe

clean:
	rm sayi_tahmin_oyunu.out sayi_tahmin_oyunu.exe
