main:
	gcc ip_adresi_kontrolcusu.c -o ip_adresi_kontrolcusu.out

windows:
	x86_64-w64-mingw32-gcc ip_adresi_kontrolcusu.c -o ip_adresi_kontrolcusu.exe

run:
	./ip_adresi_kontrolcusu.out

run_windows:
	wine ./ip_adresi_kontrolcusu.exe

clean:
	rm ip_adresi_kontrolcusu.out ip_adresi_kontrolcusu.exe