main:
	gcc url_ayristirici.c -o url_ayristirici.out

windows:
	x86_64-w64-mingw32-gcc url_ayristirici.c -o url_ayristirici.exe

run:
	./url_ayristirici.out

run_windows:
	wine ./url_ayristirici.exe

clean:
	rm url_ayristirici.out url_ayristirici.exe