main:
	gcc giris_ortalamasi.c -o giris_ortalamasi.out

windows:
	x86_64-w64-mingw32-gcc giris_ortalamasi.c -o giris_ortalamasi.exe

run:
	./giris_ortalamasi.out

run_windows:
	wine ./giris_ortalamasi.exe

clean:
	rm giris_ortalamasi.out giris_ortalamasi.exe